### PR TITLE
adding networks & container names

### PR DESCRIPTION
**Pull request by GreyAragami**

### CODE REVIEW

**Comment by acrollet** [comment]
Hi @GreyAragami, thanks for the contribution! I had a quick try but get this:

`rfa-docker acrollet$ docker-compose build
ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for networks: 'frontend'
Unsupported config option for db: 'networks'
Unsupported config option for web: 'networks'
`

I'm using the latest version of docker/compose for mac

**Comment by GreyAragami** [comment]
Oh it might be because the current version of the docker-compose file, networks are not supported.  
```
version: '2'
services:
```
Adding that on top should do the trick

Links are deprecated right now so it might be a good idea to switch entirely to networks too: https://docs.docker.com/engine/userguide/networking/default_network/dockerlinks/

**Comment by acrollet** [comment]
I'm open to that, could you update the PR?

**Comment by GreyAragami** [comment]
It should be fine now, I'm quite new to PR and contributing. Hope it helps

**Comment by GreyAragami** [comment]
Here I thought it would be a quick fix. It seems that there are some things that are missing. I'm looking into it right now.

Edit: I'll reopen this PR once I've fixed it.

**Pull request closed without merging**
